# Generated by Django 3.1 on 2020-08-27 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200827_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
